kind: Service
apiVersion: v1
metadata:
  name: postgres-modmail
  namespace: A-NAMESPACE-HERE
spec:
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: postgres
  type: ClusterIP